### ISSUE TITLE
Peer Review  - Otobo Ujah - Lab01 #2

### ISSUE THREAD

**Issue by oujah** [negarmaleki96/progdata-class#2]
Peer Review of Lab01 for Negar Maleki
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** |:heavy_check_mark:  | | |
**Presentation: graphs** | | |  |
**Presentation: tables** | :heavy_check_mark:|  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |

Remarks:
Great job.  I like how you included the image with R and Python.

**Comment by negarmaleki96** [comment]
Thank you, Otobo.
