### ISSUE TITLE
Peer Review- Angelina Venetto- Lab 2

### ISSUE THREAD

**Issue by avenetto** [negarmaleki96/progdata-class#3]
Peer Review of Lab 2 file 
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: |  | |
**Presentation: graphs** | :heavy_check_mark: | |  |
**Presentation: tables** | :heavy_check_mark: |  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *You did a great job of going above and beyond creating advanced ggplots for the plastic waste data*
- *Some specific praise?- very nice with the font and pdf layout *
- *Something I learned?- You made such cool plots, many I did not know how to do before. Also didnt know you could save as such a nice pdf
- *Specific constructive criticism?- I honestly have none, maybe if you save as a pdf make it  plot per page.
- *Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.- This was excellent

**Comment by negarmaleki96** [comment]
Thank you, Angelina!
