### ISSUE TITLE
Peer Review - Allison Perusse

### ISSUE THREAD

**Issue by aeperusse** [negarmaleki96/progdata-class#4]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- * Your coding for this lab was clean and accessible. You answered all the questions, and because there were no graphs I gave you full marks on that one too. Good job! *

**Comment by negarmaleki96** [comment]
Thank you Allison!
