### ISSUE TITLE
Cassandra Richardson - Peer Review of Lab 1 for Negar Maleki

### ISSUE THREAD

**Issue by cassrichardson** [negarmaleki96/progdata-class#5]
Cassandra Richardson - Peer Review of Lab 1 for Negar Maleki
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job on lab 1! Your code is simple, clear and easy to read.*
- *I like how you added comments to explain what each code chunk was doing.*
- *Your code taught me about the ncol() and nrow() functions to get the count of columns and rows.* 
- *Your README is great too! What's the verdict? R or Python?*

**Comment by negarmaleki96** [comment]
Honestly, I enjoy Python😁
However, R does a great job of creating plots.
