### ISSUE TITLE
Peer review for Lab 2

### ISSUE THREAD

**Issue by KiprasVarkala** [negarmaleki96/progdata-class#6]
Peer Review of Lab 2 for Negar Maleki
----------------------------------------------------
  Topic | Excellent | Satisfactory | Needs Work |
  ----------------------------|-----|-----|-----|
  **Coding style** | :heavy_check_mark: | | |
  **Coding strategy** | :heavy_check_mark: | | 
  **Presentation: graphs** | :heavy_check_mark: |
  **Presentation: tables** | :heavy_check_mark: | |
  **Achievement, creativity** | :heavy_check_mark: | | |
  **Ease of access** | :heavy_check_mark: | | |

  Remarks:
  - *Code is simple and straightforward. Great work overall!*
  - *I like how you separate out your lines of code to make it easier to read*
  - *I learned some neat things from the reference you provided*
  - *No issues found*
  - *I have learned that it is best leave comments within the code as you go along so that both others and you can understand what is being done at every step of the way.*

**Comment by negarmaleki96** [comment]
Thanks
